import { GraphQLString, GraphQLNonNull } from 'graphql';
import models from '../../../models';
export default {
Query: {
  football :(root, args) => {
    return models.footballers.findAll({attributes:['name','nationality','nationalPosition',
    'nationalKit',
    'club',
    'clubPosition',
    'clubKit',
    'clubJoining',
    'contractExpiry',
    'rating',
    'height',
    'weight',
    'prefferedFoot',
    'birthDate',
    'age',
    'prefferedPosition',
    'workRate',
    'weakFoot',
    'skillMoves',
    'ballControl',
    'dribbling',
    'marking',
    'slidingTackle',
    'standingTackle',
    'aggression',
    'reactions',
    'attackingPosition',
    'interceptions',
    'vision',
    'composure',
    'crossing',
    'shortPass',
    'longPass',
    'acceleration',
    'speed',
    'stamina',
    'strength',
    'balance',
    'agility',
    'jumping',
    'heading',
    'shotPower',
    'finishing',
    'longShots',
    'curve',
    'freekickAccuracy',
    'penalties',
    'volleys',
    'gkPositioning',
    'gkDiving',
    'gkKicking',
    'gkHandling',
    'gkReflexes']});
  },
}
};
